name: Sync with upstream
on:
  schedule:
    - cron: "30 22 * * *"
  workflow_dispatch:
permissions:
  contents: write

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Sync Repo
        run: gh repo sync ${{ github.repository }} -b main --source "LSPosed/MagiskOnWSALocal"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
